config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get '/about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 6, maximum: 30}
    validates :description, presence: true, length: {minimum: 10, maximum: 500}
    
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save {self.email = email.downcase}
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX}
    has_secure_password
    validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action."
            redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]


    def index
        @articles = Article.all
    end

    def show 
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        # for security purpose so that it accepts data from the form only
        @article = Article.new(articles_params)
        @article.user = current_user
         if @article.save
            flash[:notice] = "Article was created successfully"
            # redirect_to article_path(@article) #(both are the same things)
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        if @article.update(articles_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def articles_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own articles."
            redirect_to @article
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:show, :index]
    def new
        @category = Category.new()
    end

    def create
       @category = Category.new(category_params) 
       if @category.save
        flash[:notice] = "Category was successfully created."
        redirect_to @category
       else
        render 'new'
       end
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles
    end

    def index
        @categories = Category.all
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name updated successfully."
            redirect_to @category
        else
            render 'edit'
        end
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admin can perform that action."
            redirect_to categories_path
        end
    end

    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if logged_in?
	end

	def about
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase) ? User.find_by(email: params[:session][:email].downcase) : User.find_by(username: params[:session][:username].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged  in successfully."
            redirect_to user
        else
            flash.now[:alert] = "Entered email or password is incorrect."
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged Out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def show
        @articles = @user.articles
    end

    def edit
    end

    def index
        @users = User.all
    end
    

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to Alpha Blog #{@user.username}, you have successfully signed up."
            redirect_to @user
        else
            # we can use :new in place of 'new'
            render 'new'
        end
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated."
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles successfully deleted."
        redirect_to articles_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own profile."
            redirect_to @user
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end

    def current_user
        session[:user_id] = 1
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end
end

app/views/articles/_article.html.erb
<div class="container mb-4">
    <% @articles.each do |article| %>
        <div class="row justify-content-center">
            <div class = "col-8 mt-4">
                <div class="card text-center shadow mb*5 bg-white rounded">
                <div class="card-header fst-italic">
                    by <%= link_to article.user.username, article.user, class:"links" %>
                    <% if article.categories.any? %>
                        <div class="mt-2">
                            <%= render article.categories %>
                        </div>
                    <% end %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "link-success" %></h5>
                    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                    <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
                    <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                        <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
                        <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(article.created_at) %> ago,
                        edited <%= time_ago_in_words(article.updated_at) %> ago 
                    </small>
                </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
        <%= render 'shared/errors', obj: @article %>
            <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
                <div class="row mb-3">
                    <%= f.label :title, class: "col-sm-2 col-form-label text-light" %></br>
                    <div class="col-sm-10">
                        <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
                    </div>
                </div>
                <div class="row mb-3">
                    <%= f.label :description, class: "col-sm-2 col-form-label text-light" %></br>
                    <div class="col-sm-10">
                        <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
                    </div>
                </div>

                <div class="row mb-3">
                    <%= f.label :category, class: "col-sm-2 col-form-label text-light" %></br>
                    <div class="col-sm-10">
                        <%= f.collection_select(:category_ids, Category.all, :id, :name, 
                            { prompt: "Make your selection from below(can be empty)"}, { multiple: true, size: 4, class: "form-select shadow rounded" }) %>
                    </div>
                </div>

                <div class="row mb-3 justify-content-center">
                    <%= f.submit class: "btn btn-outline-light btn-lg col-2" %>
                </div>
            <% end %>
            <div class="row justify-content-center">
                <div class="col-sm-4 text-center mb-4">
                    <%= link_to '[ Cancel and Return to Articles Listing ]', articles_path, class: "link-info" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing All Articles</h1>
<%= render 'article' %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>
    

app/views/articles/show.html.erb
<div class="container">
    <h2 class="text-center mt-4"><%= @article.title %></h2>
    <div class="row justify-content-center">
        <div class = "col-6">
            <div class="card text-center shadow mb*5 bg-white rounded">
            <div class="card-header fst-italic">
                by <%= @article.user.username %>
                <%= link_to gravatar_for(@article.user), @article.user %>
                <% if @article.categories.any? %>
                    <div class="mt-2">
                        <%= render @article.categories %>
                    </div>
                <% end %>
            </div>
            <div class="card-body">
                <h5 class="card-title"><%= link_to @article.title, article_path(@article), class: "text-success" %></h5>
                <div class="card-text mb-2 text-start"><%= simple_format(@article.description) %></div>
                <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
                    <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
                    edited <%= time_ago_in_words(@article.updated_at) %> ago 
                    </small>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info me-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
    <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="row mb-3">
            <%= f.label :name, "Category Name", class: "col-sm-2 col-form-label text-light" %></br>
            <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name" %>
            </div>
        </div>
        <div class="row mb-3 justify-content-center">
            <%= f.submit class: "btn btn-outline-light btn-lg col-2" %>
        </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit Category Name</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
        <%= render 'form' %>
        <div class="row justify-content-center">
            <div class="col-sm-4 text-center mb-4">
                <%= link_to '[ Cancel and Return to Category ]', category_path(@category), class: "link-info" %>
            </div>
        </div>
        </div>
    </div>
</div>
    

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories Listing</h1>
<div class="container mb-4">
    <% @categories.each do |category| %>
        <div class="row justify-content-center">
            <div class = "col-5 mt-4">
                <div class="card text-center shadow mb*5 bg-white rounded">
               
                <div class="card-body">
                    <h5 class="card-title"><%= link_to category.name, category_path(category), class: "link-success" %></h5>
                    <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
                </div>
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(category.created_at) %> ago,
                        edited <%= time_ago_in_words(category.updated_at) %> ago 
                    </small>
                </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a Category</h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
        <%= render 'form' %>
        <div class="row justify-content-center">
            <div class="col-sm-4 text-center mb-4">
                <%= link_to '[ Cancel and Return to Categories Listing ]', categories_path, class: "link-info" %>
            </div>
        </div>
        </div>
    </div>
</div>
    
    

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
        <%= link_to 'Edit category name', edit_category_path(@category), class: "btn btn-outline-info " %>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>
<%= render 'articles/article' %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-secondary text-white-50">
<div class="container text-center">
  <small>Copyright &copy; <%= link_to'Wrapstore', "https://www.wrapstore.in", class: "link-light" %></small>
</div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name,msg| %>
        <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
            <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
</div>

app/views/layouts/_navigations.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'ALPHA BLOG', root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Bloggers', users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <li><%= link_to 'Create new article', new_article_path, class: "dropdown-item" %>
            <% end %>
            <li><%= link_to 'View Articles', articles_path, class: "dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to 'Create new category', new_category_path, class: "dropdown-item" %>
            <% end %>
            <li><%= link_to 'View Categories', categories_path, class: "dropdown-item" %>
          </ul>
        </li>

        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'View Profile', user_path(current_user), class: "dropdown-item" %>
            <li><%= link_to 'Edit Profile', edit_user_path(current_user), class: "dropdown-item" %>
            <li><%= link_to 'Delete Profile', user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
          </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Alpha Blog</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  
  </head>
  <body class="d-flex flex-column">
    <div id="page-content">
      <%= render 'layouts/navigations' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>
<%= link_to 'Articles Listing', articles_path %> 
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="container">
    <div class="jumbotron text-center text-white" id="home-container">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved.</h4>
        <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
        <%= render 'shared/errors', obj: @user %>
            <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
                <div class="row mb-3">
                    <%= f.label :username, class: "col-sm-2 col-form-label text-light" %></br>
                    <div class="col-sm-10">
                        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
                    </div>
                </div>
                <div class="row mb-3">
                    <%= f.label :email, class: "col-sm-2 col-form-label text-light" %></br>
                    <div class="col-sm-10">
                        <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
                    </div>
                </div>
                <div class="row mb-3">
                    <%= f.label :password, class: "col-sm-2 col-form-label text-light" %></br>
                    <div class="col-sm-10">
                        <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
                    </div>
                </div>
                <div class="row mb-3 justify-content-center">
                    <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: "btn btn-outline-light btn-lg col-2") %>
                </div>
            <% end %>
            <div class="row justify-content-center">
                <div class="col-sm-4 text-center mb-4">
                    <%= link_to '[ Cancel and Return to Users Listing ]', users_path, class: "link-info" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Update Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container mb-4">
    <% @users.each do |user| %>
        <div class="row justify-content-center">
            <div class = "col-8 mt-4">
                <div class="card text-center shadow mb*5 bg-white rounded">
                <div class="card-header fst-italic">
                    <%= link_to user.username, user %>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <%= link_to gravatar_for(user, size: 150), user%>
                    </h5>
                    <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
                    <%= link_to 'View Profile', user, class: "btn btn-outline-success" %>
                    <% if logged_in? %>
                        <% if user == current_user %>
                            <%= link_to 'Edit Profile', edit_user_path(user), class: "btn btn-outline-info" %>
                        <% end %>
                        <% if current_user.admin? %>
                            <%= link_to 'Delete Profile', user_path(user), class: "btn btn-outline-danger", method: :delete,
                            data: {confirm: "Are you sure you want to delete the user and all associated articles?"} %>
                        <% end %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>Joined <%= time_ago_in_words(user.created_at) %> ago 
                    </small>
                </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up for Alpha Blog</h1>
<%= render 'form' %>
    

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
        <%= link_to 'Edit your profile', edit_user_path(@user), class: "btn btn-outline-info " %>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>
<%= render 'articles/article' %>